development: &defaults
  adapter: postgresql
  host: localhost
  username: postgres
  password: meurio_dev
  database: meu_rio_development

test: &test
  host: 127.0.0.1
  database: meurio_test
  adapter: postgresql
  username: postgres

